### ISSUE TITLE
Why is type 'culprit' not 'Culprit'?

### ISSUE THREAD

**Issue by ArcticSnowman** [bndr/gojenkins#102]
Why is type 'culprit' not 'Culprit'?

Seems odd to have a structure type not follow the case rules..

Also it prevent the godoc from showing it in the documentation page and you don't have a nice link from the build.GetCulprits() function definition.

**Comment by ArcticSnowman** [comment]
This in fact breaks the GetCulprits() as you can't pass the return array around as the 'type' is not exported..

**Comment by ArcticSnowman** [comment]
PR #103 to fix

**Comment by supereagle** [comment]
Agree.
> Seems odd to have a structure type not follow the case rules..
> Also it prevent the godoc from showing it in the documentation page and you don't have a nice link from the build.GetCulprits() function definition.


Even `culprit` is not exported, `GetCulprits()` also can correctly work.
> This in fact breaks the GetCulprits() as you can't pass the return array around as the 'type' is not exported..

**Comment by ArcticSnowman** [comment]
OK fixed with the merge of the PR
