### ISSUE TITLE
the `build` struct can't be marshaled. 

### ISSUE THREAD

**Issue by bbbmj** [bndr/gojenkins#109]
![image](https://user-images.githubusercontent.com/29789939/32206570-dcdee810-be30-11e7-9358-954bf94c05a1.png)
![image](https://user-images.githubusercontent.com/29789939/32206585-f5b3f13c-be30-11e7-880c-fb8bf26edf12.png)

**Comment by zz-bmj** [comment]
`Build.Jenkins.Requester` give rise to this error.

**Comment by strmjb** [comment]
BuildResponse can be marshaled by passing json.Marshal(build.Raw). If you are attempting to export the data retrieved from Jenkins, it is best to output the raw Jenkins build response as JSON or to define your own exportable data structure.
