### ISSUE TITLE
Add token authentication

### ISSUE THREAD

**Issue by philippgille** [bndr/gojenkins#137]
Currently there's only `gojenkins.CreateJenkins(nil, "http://localhost:8080/", "admin", "secret")` for authentication. But in some cases, for example in companies where the employees log in to Jenkins with an LDAP account or other Single-Sign-On credentials, you don't want to have your SSO credentials flying around.

Jenkins has a feature where you can create a *token* for your credentials and then use that for authentication in HTTP requests.

This issue is for adding support for this kind of Jenkins token to this package.

**Comment by arinto** [comment]
Yup, it works, we should close this issue 👍 
ping @bndr

**Comment by philippgille** [comment]
You're right, it works, I guess I was confused by the parameter name and method documentation (not mentioning Jenkins tokens). Maybe this this can be improved, so everyone reading the docs know that tokens are supported?
