### ISSUE TITLE
GetResultSet() returns "no result sets found" when iterating over builds

### ISSUE THREAD

**Issue by eanxgeek** [bndr/gojenkins#16]
I have two programs that do exactly the same thing with one exception.  Program 1 hardcodes buildId while program 2 iterates over builds and assigns buildId := build.Number.

In program 1, I get back the expected values for PassCount and FailCount, when I run Program 2, when the same buildId is encountered I get "No reset set"

**Program 1:**
```
buildId = 467

	data, _ := jenkins.GetBuild(jobName, buildId)

	//data.Poll()
	resultSet, _ := data.GetResultSet()
	if resultSet != nil {
		fmt.Println(buildId, " Pass count : ", resultSet.PassCount, " Fail count : ", resultSet.FailCount)
	}
```
>467  Pass count :  2399  Fail count :  25

**Program 2:**
```
for _, build := range builds {
		buildId = build.Number

		data, _ := jenkins.GetBuild(jobName, buildId)
		data.Poll()
		resultSet, _ := data.GetResultSet()
		fmt.Println(buildId, " : ")
		if resultSet != nil {
			fmt.Println(buildId, " Pass count : ", resultSet.PassCount, " Fail count : ", resultSet.FailCount)
		} else {
			continue
		}
	}
```
> 470  : 
> 469  : 
> 468  : 
> 467  : 
> 466  : 

I have tried numerous approaches and always the same.  You'll notice I even tried data.Poll() in program 2.  Nothing has worked address the issue.

**Comment by bndr** [comment]
I don't see any reason why it should fail in a loop.

How are you getting your builds?
```for _, build := range builds {```

**Comment by eanxgeek** [comment]
yes, exactly as shown above and as you have captured.  From that for {} loop I then have:

```
var buildId int64
for _, build := range builds {
   buildId = build.Number
...
}
```
I have also tried using:
```
buildId := build.Number
```
Same results.
I'm not sure why it would make any difference but I'm thinking about trying to create a separate function, within my code, with args buildId and returns a *resultSet

func getResultSet(buildId int64) *resultSet {
...
}

Thoughts?

**Comment by eanxgeek** [comment]
I am attempting your working code, and still I see the same results.
'''
func main() {

	url := "localhost:8080/"
	jobName := "dtests-jamq-700-candidate-tests-results"

	jenkins := gojenkins.CreateJenkins(url)
	_, err := jenkins.Init()

	if err != nil {
		panic("err")
	}

	job, err := jenkins.GetJob(jobName)

	if err != nil {
		panic(err)
	}

	builds, err := job.GetAllBuildIds()

	if err != nil {	
		panic(err)
	}
	
	for _, buildID := range builds {

		build, _ := jenkins.GetBuild(jobName, buildID.Number)

		resultSet, _ := build.GetResultSet()
               // I use this approach instead of checking err, because some builds have no result sets.
               // when this occurs err != nil and panic() would cause the program to unnecessarily exit.
               // Will attempt to use if err != nil { fmt.Println(err) } to avoid unnecessary exit, but
               // expect same results.
		if resultSet != nil {
			fmt.Println(buildID.Number, " Pass count : ", resultSet.PassCount, " Fail count : ", resultSet.FailCount)
		} else {
			fmt.Println(buildID.Number, " No Result Set")
		}
	}
}
```

**Comment by eanxgeek** [comment]
This problem was apparently fixed in one of the updates you did yesterday and my larger program was apparently still using the older version.  Over-sight on my part - My apologies, everything seems to work with the latest code.

**Comment by bndr** [comment]
Good to know that you got it working!

**Comment by akashshinde** [comment]
`GetResultSet()` call will return test result irrespective of any language test suit ? or it will only work for junit ?

**Comment by supereagle** [comment]
@akashshinde  `GetResultSet()` will return JUnit-format test results, which is just only one report style of test results, has no relationship with code languages.

**Comment by akashshinde** [comment]
@supereagle thanks, got it
