### ISSUE TITLE
GetBuild Issue - jobUrl vs jenkinsServerUrl

### ISSUE THREAD

**Issue by Waxing-Moon** [bndr/gojenkins#173]
Hi, 

My Jenkins is working behind apache.
I noticed that in https://{JENKINS_URL}/job/{JOB_NAME}/4/api/json?depth=1, the url value coming is of my private network i.e not of apache.

Example - 
In apache I am proxy passing to - https://myjenkins.priv.com (IP - https://192.168.1.3)
And in jenkins json it is coming as - https://192.168.1.2/job/{JOB_NAME}/4/

For now, I fixed it via changing some code in GetBuild Function.

`func (j *Job) GetBuild(id int64) (*Build, error) {`
`build := Build{Jenkins: j.Jenkins, Job: j, Raw: new(BuildResponse), Depth: 1, Base: "/job/" + j.Raw.Name + "/" + strconv.FormatInt(id, 10)}`
	`status, err := build.Poll()`
	`if err != nil {`
		`return nil, err`
	`}`
	`if status == 200 {`
		`return &build, nil`
	`}`
	`return nil, errors.New(strconv.Itoa(status))`
`}`

Can you please tell me, whether this issue is related to this library or it could be related to apache server?
Thanks

**Comment by SmilingNavern** [comment]
Actually it should be configured in your jenkins if it is behind proxy. Look for this answer: https://stackoverflow.com/a/9089610/4522921

**Comment by Waxing-Moon** [comment]
Thanks, on changing Jenkins URL in configure, it is working fine. :)
