### ISSUE TITLE
use semantic version for tags

### ISSUE THREAD

**Issue by zhyon404** [bndr/gojenkins#174]
like v1.0.0, so it can work with go mod, thanks~

currently v1.0. can't recognized by go mod.

golang/go#27528

**Comment by tsal** [comment]
This is a problem - the docs are for v1.0, but since the tag isn't semantic, go mods grab 0.2.0.

**Comment by neowood** [comment]
Meet the same problem, please edit the tag, thanks.

**Comment by zhyon404** [comment]
tag already added, so closed
