### ISSUE TITLE
Use "pretty=false" for JSON/XML gets?

### ISSUE THREAD

**Issue by Zoetermeer** [bndr/gojenkins#18]
Passing this along on the querystring gives a minified response and it seems like we would always prefer this.  If you think this is a good idea, I'm happy to submit a PR!

**Comment by bndr** [comment]
I think jenkins serves minified version when no parameter is specified, you can only get pretty version when you explicitly set it with pretty=true

**Comment by Zoetermeer** [comment]
Oh, you're right.  My bad.
