### ISSUE TITLE
Jenkins.Init() should check Response.StatusCode

### ISSUE THREAD

**Issue by Bpazy** [bndr/gojenkins#210]
`Jenkins.Init()` return success even if invoking `gojenkins.CraeteJenkins` with wrong auth.

Here is the example code:
```golang
jenkins, err := gojenkins.CreateJenkins(nil, "http://somejenkins.org/", "username", "some wrong token").Init()
if err != nil {
        // Never invoked but shoud be.
	fmt.Printf("%+v", err)
	return
}
```

So `Jenkins.Init()` should check Response.StatusCode: https://github.com/bndr/gojenkins/blob/65ee8c9388b5f3b986f2c79179a6696cd8705858/jenkins.go#L51-L67

The code should be written like this:
```go
func (j *Jenkins) Init() (*Jenkins, error) {
	j.initLoggers()

	// Check Connection
	j.Raw = new(ExecutorResponse)
	rsp, err := j.Requester.GetJSON("/", j.Raw, nil)
	if err != nil {
		return nil, err
	}

	j.Version = rsp.Header.Get("X-Jenkins")
	if j.Raw == nil || rsp.StatusCode != http.StatusOK { // Check rsp.StatusCode
		return nil, errors.New("Connection Failed, Please verify that the host and credentials are correct.")
	}

	return j, nil
}
```

Jenkins version: 2.176.1

**Comment by eryajf** [comment]
I have the same problem

**Comment by Bpazy** [comment]
@eryajf Maybe you can try my fork: https://github.com/Bpazy/gojenkins

**Comment by figo** [comment]
https://github.com/bndr/gojenkins/pull/214 merged, try the latest code please @eryajf

**Comment by eryajf** [comment]
> #214 merged, try the latest code please @eryajf

Thank you, it has been successful, but I have used it locally, I hope the official package can have more methods for folder operations

**Comment by vperson** [comment]
I think you should put the status code of the request in the error message
For example like this
```
	j.Version = rsp.Header.Get("X-Jenkins")
	if j.Raw == nil || rsp.StatusCode != http.StatusOK {
		return nil, errors.New(fmt.Sprintf("Connection Failed, Please verify that the host and credentials are correct, Status Code %s", rsp.StatusCode))
	}
```
