### ISSUE TITLE
GetResultSet() - "duration" in "_class": "hudson.tasks.junit.TestResult" is coming 0

### ISSUE THREAD

**Issue by saurabh-openstack** [bndr/gojenkins#227]
"duration" in "_class": "hudson.tasks.junit.TestResult" is coming 0. The type incorrectly configured to int64 while from Jenkins it is float. 
-- Jenkins API output {Jenkins URL}{JOB}testReport/api/json
"_class": "hudson.tasks.junit.TestResult",
"testActions": [],
"duration": 343.131,     <--- float 
"empty": false,
"failCount": 0,
"passCount": 394,
"skipCount": 0,

--gojenkins sdk
func (b *Build) GetResultSet() (*TestResult, error)

type TestResult struct {
	Duration  int64 `json:"duration"`.   <---- int64
	Empty     bool  `json:"empty"`
	FailCount int64 `json:"failCount"`
	PassCount int64 `json:"passCount"`
	SkipCount int64 `json:"skipCount"`

Due to mismatch of type the duration returned by GetResultSet() is coming to 0.

**Comment by figo** [comment]
Hi @saurabh-openstack  thanks for reporting, would you mind open PR with a fix?

**Comment by saurabh-openstack** [comment]
@figo Thanks a lot. I was just about to fix this but observed it is already fixed. [[FixLink]](https://github.com/bndr/gojenkins/commit/7c9e106b64aec7befc4e91426159e5a8e91b43cf). So marking this issue as fixed.
