### ISSUE TITLE
Jenkins.Init func do not need ctx

### ISSUE THREAD

**Issue by k8scat** [bndr/gojenkins#229]
```go
ctx := context.Background()
jenkins := gojenkins.CreateJenkins(nil, "http://localhost:8080/", "admin", "admin")
_, err := jenkins.Init(ctx)
```

Code above will alert that `too many arguments` for `Jenkins.Init` func, is the README demo wrong?

**Comment by figo** [comment]
If you use the latest release or master, you should expect context as parameter, thanks
https://github.com/bndr/gojenkins/releases/tag/v1.1.0
