### ISSUE TITLE
issue of README.md

### ISSUE THREAD

**Issue by sawyerming** [bndr/gojenkins#244]
Hi,
I found there is a issue in Usage of README.md ,below:
"queueid, err := jenkins.InvokeSimple(ctx, params)"
I lookinto and found InvokeSimple() is not jenkins's function, It belongs to Job. Should use Job to invoke it?
Cheers.

**Comment by bigdimple** [comment]
"jenkins.InvokeSimple(ctx, params)" should be "job.InvokeSimple(ctx, params)"
