### ISSUE TITLE
Performance issue with GetAllNodes redundant call to GetNode

### ISSUE THREAD

**Issue by chaseadamsio** [bndr/gojenkins#27]
Within `GetAllNodes`, after the API call to `/computer` is made, `GetNode` makes a request to `/computer/{name}`, which returns the same information that's in the individual nodes of the response from `/computer` that's already been received:

```
nodes := make([]*Node, len(computers.Computers))
	for i, node := range computers.Computers {
		name := node.DisplayName
		// Special Case - Master Node
		if name == "master" {
			name = "(master)"
		}
		nodes[i], _ = j.GetNode(name)
	}
```

https://github.com/bndr/gojenkins/blob/master/jenkins.go#L293-L301

As far as I know, this is not a new feature to Jenkins, so I was wondering if there was some extra sizzle that made this extra API call necessary. As you can imagine, as the list of nodes grows (I have a Master with 60 slaves, which makes this particular method creep along) the time to completion grows significantly because it's making 1 http request + n http requests based on the number of slaves in the response.

Happy to PR a change but before I do, I wanted to confirm there's not something I'm missing in how the implementation is supposed to work.

**Comment by bndr** [comment]
If the information of the individual Nodes is the same as in the response from /computer, then it's a bug :) feel free to submit a PR
