### ISSUE TITLE
should nodeResponse be exported?

### ISSUE THREAD

**Issue by chaseadamsio** [bndr/gojenkins#29]
In the case that a consumer wants to pass a reference, a user may not be able to do so because `nodeResponse` isn't exported: https://github.com/bndr/gojenkins/blob/master/node.go#L34-L61

Would it make sense to export as `NodeResponse` as there's information a user may want to get without having `poll()` that comes along with all of the methods to get the same information that would be in the nodeResponse?

**Comment by bndr** [comment]
Seems reasonable. Can you submit a PR? Would much appreciate it
