### ISSUE TITLE
Gojenkins is not Goroutine safe

### ISSUE THREAD

**Issue by Cidan** [bndr/gojenkins#35]
When making several API calls from different gorouties, I will get the following:

```
fatal error: concurrent map writes

goroutine 14 [running]:
runtime.throw(0x954850, 0x15)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82062f560 sp=0xc82062f548
runtime.mapassign1(0x8a6060, 0xc8204286f0, 0xc82062f628, 0xc82062f638)
        /usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc82062f608 sp=0xc82062f560
net/textproto.MIMEHeader.Set(0xc8204286f0, 0x905ae0, 0xc, 0x9539f0, 0x10)
        /usr/local/go/src/net/textproto/header.go:22 +0xc2 fp=0xc82062f658 sp=0xc82062f608
net/http.Header.Set(0xc8204286f0, 0x905ae0, 0xc, 0x9539f0, 0x10)
        /usr/local/go/src/net/http/header.go:31 +0x49 fp=0xc82062f688 sp=0xc82062f658
github.com/bndr/gojenkins.(*Requester).SetHeader(0xc8204242d0, 0x905ae0, 0xc, 0x9539f0, 0x10, 0x410a82)
        /git/ops/src/github.com/bndr/gojenkins/request.go:85 +0x4d fp=0xc82062f6b8 sp=0xc82062f688
github.com/bndr/gojenkins.(*Requester).GetJSON(0xc8204242d0, 0xc82068b920, 0x14, 0x77b2e0, 0xc820486c00, 0xc82012de30, 0x0, 0                                 x0, 0x0)
        /git/ops/src/github.com/bndr/gojenkins/request.go:68 +0x6c fp=0xc82062f770 sp=0xc82062f6b8
github.com/bndr/gojenkins.(*Build).Poll(0xc82012de00, 0x0, 0x0, 0x0, 0x9, 0x0, 0x0)
        /git/ops/src/github.com/bndr/gojenkins/build.go:447 +0x312 fp=0xc82062f870 sp=0xc82062f770
github.com/bndr/gojenkins.(*Job).GetBuild(0xc8205bc380, 0x46d5, 0xc8205b4450, 0x0, 0x0)
        /git/ops/src/github.com/bndr/gojenkins/job.go:104 +0x202 fp=0xc82062f968 sp=0xc82062f870
```
Is it possible to refactor this bit so it doesn't use global state?

**Comment by bndr** [comment]
Feel free to submit any Pull Requests you think will make the code better :) The more PRs the better. Currently I don't have much free time to fix this, maybe in a week or two.

**Comment by Cidan** [comment]
Sure, I'll see if I can find time, :)

**Comment by bndr** [comment]
Thanks, much appreciated :)

**Comment by vitalyisaev2** [comment]
I'm afraid there is a design problem: the `Requester`  acts like a stateful object (stores headers and HTTP response inside itself). I performed an attempt to make ```Requester``` stateless by moving all the mutable states to the new struct ```APIRequest``` (see https://github.com/vitalyisaev2/gojenkins/blob/ISSUE-35/request.go). But it seems like other top-level objects (like ```Jenkins```) are suffering from the same disease. 

I would like to use this feature-rich library in my projects, but at the moment I'm not sure if it's possible to make it completely thread-safe.

**Comment by bndr** [comment]
Yeah, when I started this library I didn't think about thread proofing the code, it was on the TODO list but I always put it off, and you are right that the whole `Requester` logic should be rewritten. 

As you have already started refactoring the code, and if you get it working with goroutines, I would very much appreciate a Pull Request.

**Comment by vitalyisaev2** [comment]
Thank you @bndr, I'll try to work it out
