### ISSUE TITLE
errors ?

### ISSUE THREAD

**Issue by boopathi** [bndr/gojenkins#4]
How do I know if `jenkins.Getjob("jobname")` returned an error ?

Shouldn't it be like this ?

```go
job, err := jenkins.Getjob("jobname")
```

And this applies to other APIs also.

**Comment by bndr** [comment]
You could check if job is nil or not
```
job := jenkins.Getjob("jobname")
if job == nil {
     //job does not exist
}
```

But you are correct, it's better to handle it with a second return parameter, i'll put it on my todo list.

**Comment by boopathi** [comment]
Have tried something, and seems to build properly. Haven't tested it properly though. 

https://github.com/boopathi/gojenkins/commit/5b9ee6a3218df474ca64d9ebf25f1df29ebfc032

Will test it with some servers and get back with results.

Would be happy to send a PR, but go doesn't allow versioning or freezing commits/tags in a project for its dependencies. `go get` always fetches the latest version from the master branch of the repo. So, this API change would break all the existing clients of gojenkins.

**Comment by boopathi** [comment]
There is still a lot of places to be changed. Changing them slowly in my master branch.

**Comment by bndr** [comment]
This will definitely break the API, but I think this is the right direction to go. Fell free to submit a pull request, although it will take some time for me to review your changes, update the docs etc.
