### ISSUE TITLE
Proposal: Support Jenkins labels

### ISSUE THREAD

**Issue by supereagle** [bndr/gojenkins#50]
Sometimes we need to manage nodes by labels, I think there is need to add these APIs to support Jenkins labels.

I have done some [investigation](https://github.com/supereagle/gojenkins/commit/d23256e4296ced9094b9561099fec47cdf3a187b) on my forked repo, and it works as expected.

@bndr  WDYT?

**Comment by bndr** [comment]
Sounds good, you can open up a pull request! Write some tests for your methods and i will merge the code.

**Comment by supereagle** [comment]
@bndr OK. Thanks.

**Comment by VijayNagulakonda** [comment]
I have couple of questions for this supported feature, 
1. When we do `jenkins.Raw.AssignedLabels` is it expected to give labels for only master node? if yes, how to get child node labels?
2. When we do `jenkins.GetLabel(ctx, "XYZ_label")` this returns all the nodes which have that specific label, but is there a way we  can get complete list of labels that are being used in jenkins including child nodes?
