### ISSUE TITLE
Support Jenkins with CSRF enabled

### ISSUE THREAD

**Issue by TamalSaha** [bndr/gojenkins#63]
Hi,
Jenkins 2.x by default enable CSRF. This requires passing an extra Header value with each api call. 
https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API#RemoteaccessAPI-CSRFProtection

Can this be supported? I am willing to send prs for this.

Thanks.

**Comment by bndr** [comment]
Sure, send the PRs, as long as it doesn't break backwards compatibility. 

Tests for the functionality would also be much appreciated.

**Comment by TamalSaha** [comment]
Good news! Crumb seems to be already supported. It is just that there is not indication in the api. https://github.com/bndr/gojenkins/blob/master/request.go#L61

**Comment by mbelang** [comment]
Hey guys, we need that feature but it's been a long time since you did a release. We currently pull the master branch in our dependency which is a bit bad. Can you do an official release please.

Thanks.
