### ISSUE TITLE
Error message in job.go has missing argument

### ISSUE THREAD

**Issue by client9** [bndr/gojenkins#7]
Found via govet

```
github.com/bndr/gojenkins/job.go:387: missing argument for Sprintf("%s"): format reads arg 2, have only 1 args
```

```go
	if isRunning && skipIfRunning {
		return false, errors.New(fmt.Sprintf("%s Will not request new build because %s is already running", j.GetName()))
	}
```

Im not quite sure what the other arg is suppose to be, otherwise I'll send in a pull request.

Also `errors.New(fmt.Sprintf(` is fine but clunky.  Perhaps`fmt.Errorf` would be better.

thanks for a fine project!

n

**Comment by bndr** [comment]
Yeah, that's a bug, should be "Will not request new build because %s is already running". 

Feel free to change `errors.New(fmt.Sprintf(` to `fmt.Errorf`. I accept all pull requests that make the project better. :)
