### ISSUE TITLE
how to pass parameter

### ISSUE THREAD

**Issue by laimu** [bndr/gojenkins#87]
Hi, I'm use BuildJob method to pass parameter, but jenkins not received.
my code is : 

params := make(map[string]string)
			params["param1"] = "ssss"
			params["param2"] = "bbbb"
res, err := util.Build("test_parameter",params)

the util code is : 
func Build(appName string, options ...interface{}) (bool, error) {
ret, err := jenkinsClent.BuildJob(appName, options)
}

I don't know where is wrong.

**Comment by supereagle** [comment]
I think the usage is correct. As not sure what is the job config, I can not directly find the root cause. 
You can refer to [goline](job.InvokeSimple(params)) and have a try on `job.InvokeSimple(params)`.

**Comment by laimu** [comment]
@supereagle You are right, my util code is wrong.I find the problem is that the parameter must not be "options ...interface{}" , I change the parameter to map[string]string,  the code be
func Build(appName string, options map[string]string}) (bool, error) {
ret, err := jenkinsClent.BuildJob(appName, options)
}
that job worked! Thank you very much!

**Comment by supereagle** [comment]
Glad to hear that it has been fixed.
